---
- name: Update APT package w/ manager repo cache
  apt:
    update_cache: yes

- name: Installing Default OpenJDK Java
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    default-jdk

- name: Installing GNUPG
  apt:
    name: gnupg 
    update_cache: yes 

- name: Install apache2 with apt
  apt:
   name: apache2
   update_cache: yes
 
- name: Starting apache2
  service:
   name: apache2
   state: started
   


  
    
